-- Stores daily study tasks generated by kalnehi
create table if not exists daily_tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade,
  topic_id integer,
  subject text,
  topic text,
  duration_minutes int,
  scheduled_date date,
  status text default 'pending',
  created_at timestamp default now()
);

-- Stores revision schedule
create table if not exists revision_queue (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade,
  topic_id integer,
  next_revision date,
  interval_days int default 3,
  created_at timestamp default now()
);

-- Stores daily activity logs
create table if not exists daily_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade,
  log_date date default current_date,
  study_minutes int default 0,
  tasks_completed int default 0,
  tasks_missed int default 0,
  notes text,
  created_at timestamp default now()
);